import java.util.ArrayList;
import java.util.Scanner;

/**
 * Entry point for the Aider chatbot application.
 */
public class Aider {
    /** Separates the chatbot's responses in the console. */
    private static final String SEPARATOR = "____________________________________________________________";

    /** The banner displayed when the chatbot starts. */
    private static final String BANNER = "    _    ___ ____  _____ ____ \n"
            + "   / \\  |_ _|  _ \\| ____|  _ \\ \n"
            + "  / _ \\  | || | | |  _| | |_) |\n"
            + " / ___ \\ | || |_| | |___|  _ < \n"
            + "/_/   \\_\\___|____/|_____|_| \\_\\";

    /** The tasks currently managed by the application. */
    private static final ArrayList<Task> TASKS = new ArrayList<>();

    /**
     * Processes one command and returns the response shown to the user interface.
     *
     * @param command the command entered by the user
     * @return the response generated by the command
     */
    public static String processCommand(String command) throws AiderException {
        if (command.equals("bye")) {
            return "Bye. Hope to see you again soon!";
        }

        if (command.equals("list")) {
            StringBuilder response = new StringBuilder("Here are the tasks in your list:");
            for (int i = 0; i < TASKS.size(); i++) {
                response.append("\n").append(i + 1).append(".").append(TASKS.get(i));
            }
            return response.toString();
        }

        if (command.equals("mark") || command.startsWith("mark ")) {
            int taskIndex = getTaskIndex(command, "mark", TASKS.size());
            TASKS.get(taskIndex).markAsDone();
            return "Nice! I've marked this task as done:\n  " + TASKS.get(taskIndex);
        }

        if (command.equals("unmark") || command.startsWith("unmark ")) {
            int taskIndex = getTaskIndex(command, "unmark", TASKS.size());
            TASKS.get(taskIndex).markAsNotDone();
            return "OK, I've marked this task as not done yet:\n  " + TASKS.get(taskIndex);
        }

        if (command.equals("delete") || command.startsWith("delete ")) {
            int taskIndex = getTaskIndex(command, "delete", TASKS.size());
            Task removedTask = TASKS.remove(taskIndex);
            return "Noted. I've removed this task:\n  " + removedTask
                    + "\nNow you have " + TASKS.size() + " tasks in the list.";
        }

        Task newTask = createTask(command);
        TASKS.add(newTask);
        return "Got it. I've added this task:\n  " + newTask
                + "\nNow you have " + TASKS.size() + " tasks in the list.";
    }

    public static void main(String[] args) {
        System.out.println(SEPARATOR);
        System.out.println(BANNER);
        System.out.println("Hello! I'm Aider.");
        System.out.println("What can I do for you?");
        System.out.println(SEPARATOR);

        Scanner scanner = new Scanner(System.in);
        while (scanner.hasNextLine()) {
            String command = scanner.nextLine().trim();
            System.out.println(SEPARATOR);

            try {
                System.out.println(processCommand(command));
                if (command.equals("bye")) {
                    break;
                }
            } catch (AiderException exception) {
                System.out.println("OOPS!!! " + exception.getMessage());
            }

            System.out.println(SEPARATOR);
        }
    }

    /**
     * Creates the appropriate task subtype from a user command.
     *
     * @param command the complete command entered by the user
     * @return the task represented by the command
     */
    private static Task createTask(String command) throws AiderException {
        if (command.equals("todo") || command.startsWith("todo ")) {
            String description = command.substring("todo".length()).trim();
            if (description.isEmpty()) {
                throw new AiderException("A todo needs a description, for example: todo read book.");
            }
            return new Todo(description);
        }

        if (command.equals("deadline") || command.startsWith("deadline ")) {
            String details = command.substring("deadline".length()).trim();
            int byIndex = details.indexOf(" /by ");
            if (byIndex < 0) {
                throw new AiderException("A deadline must include a description and a /by date or time.");
            }

            String description = details.substring(0, byIndex).trim();
            String by = details.substring(byIndex + " /by ".length()).trim();
            if (description.isEmpty() || by.isEmpty()) {
                throw new AiderException("A deadline needs a description and a date or time after /by.");
            }
            return new Deadline(description, by);
        }

        if (command.equals("event") || command.startsWith("event ")) {
            String details = command.substring("event".length()).trim();
            int fromIndex = details.indexOf(" /from ");
            int toIndex = details.indexOf(" /to ");
            if (fromIndex < 0 || toIndex <= fromIndex) {
                throw new AiderException("An event needs a description, /from time, and /to time.");
            }

            String description = details.substring(0, fromIndex).trim();
            String from = details.substring(fromIndex + " /from ".length(), toIndex).trim();
            String to = details.substring(toIndex + " /to ".length()).trim();
            if (description.isEmpty() || from.isEmpty() || to.isEmpty()) {
                throw new AiderException("An event needs text after its description, /from, and /to markers.");
            }
            return new Event(description, from, to);
        }

        throw new AiderException("I don't recognize that command. Try todo, deadline, event, list, mark, "
                + "unmark, or delete.");
    }

    /**
     * Parses and validates a task number from a mark or unmark command.
     *
     * @param command the complete command entered by the user
     * @param commandName the command name being parsed
     * @param taskCount the number of tasks currently stored
     * @return the zero-based index of the selected task
     * @throws AiderException if the command does not contain a valid task number
     */
    private static int getTaskIndex(String command, String commandName, int taskCount)
            throws AiderException {
        String taskNumberText = command.substring(commandName.length()).trim();
        if (taskNumberText.isEmpty()) {
            throw new AiderException("The " + commandName + " command needs a task number.");
        }

        final int taskNumber;
        try {
            taskNumber = Integer.parseInt(taskNumberText);
        } catch (NumberFormatException exception) {
            throw new AiderException("The " + commandName + " command needs a whole-number task number.");
        }

        int taskIndex = taskNumber - 1;
        if (taskIndex < 0 || taskIndex >= taskCount) {
            throw new AiderException("That task number does not exist.");
        }
        return taskIndex;
    }
}
